### ISSUE TITLE
Final boss Implementation

### ISSUE THREAD

**Issue by AliAlnajja** [NicholasCiobanu/GameProgFinalProject#58]
# Description
Final Boss implementations

# Tasks

- [x] Task 1 Get new sets of zombies with implemented faces
- [x] Task 2 Add different suits for each character
- [x] Task 3 Add the developers
- [x]  Task4 Implement scene transfer
- [ ]  Task5 Add health and damage dealing
- [x]  Task6 Make the zombies follow the player
- [x] Task7 Add sound bits 
- [x] Task8 Add backround music
- [x] Task9 Add cut scenes
